version: '3.8'
services:
  spark-master:
    image: 'bitnami/spark:latest'
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - '7000:8080'
      - '7077:7077'
    volumes:  
      - './apps:/opt/bitnami/spark/apps'
      - './data:/opt/bitnami/spark/data'
      - './requirements.txt:/opt/bitnami/spark/requirements.txt'
    command: >
          bash -c "pip3 install -r /opt/bitnami/spark/requirements.txt &&
           /opt/bitnami/spark/bin/spark-submit --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.0 \
           /opt/bitnami/spark/apps/kafka_spark_streaming.py"
    networks:
      - network

  spark-worker1:
    image: 'bitnami/spark:latest'
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=4G
      - SPARK_DAEMON_MEMORY=1G
    ports:
      - '7001:8081'
    volumes:
      - './apps:/opt/bitnami/spark/apps'
      - './data:/opt/bitnami/spark/data'
    depends_on:
      - spark-master
    networks:
      - network

  spark-worker2:
    image: 'bitnami/spark:latest'
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=4G
      - SPARK_DAEMON_MEMORY=1G
    ports:
      - '7002:8081'
    volumes:
      - './apps:/opt/bitnami/spark/apps'
      - './data:/opt/bitnami/spark/data'
    depends_on:
      - spark-master
    networks:
      - network

networks:
  network:
    external: true

