version: '3.8'
services:
  spark-master:
    build: .
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - '7000:8080'
      - '7077:7077'
    volumes:  
      - './apps:/home/spark/apps'
      - './data:/home/spark/data'
    # command: >
    #   bash -c "tail -f /dev/null"
    networks:
      - network

  spark-worker1:
    build: .
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=4G
      - SPARK_DAEMON_MEMORY=1G
    ports:
      - '7001:8081'
    volumes:
      - './apps:/home/spark/apps'
      - './data:/home/spark/data'
    depends_on:
      - spark-master
    networks:
      - network

  spark-worker2:
    build: .
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=4G
      - SPARK_DAEMON_MEMORY=1G
    ports:
      - '7002:8081'
    volumes:
      - './apps:/home/spark/apps'
      - './data:/home/spark/data'
    depends_on:
      - spark-master
    networks:
      - network

networks:
  network:
    external: true


