version: '3'
services:
  spark-master:
    image: 'bitnami/spark:latest'
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - '8080:8080'
      - '7077:7077'
    volumes:
      - '/var/www/trend_metrics/spark/logs:/opt/bitnami/spark/logs'
      - '/var/www/trend_metrics/spark/conf:/opt/bitnami/spark/conf'
      - '/var/www/trend_metrics/spark/apps:/opt/spark-apps'
      - '/var/www/trend_metrics/spark/data:/opt/spark-data'
    networks:
      - network

  spark-worker:
    image: 'bitnami/spark:latest'
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1G
      - SPARK_DAEMON_MEMORY=1G
    ports:
      - '8081:8081'
    volumes:
      - '/var/www/trend_metrics/spark/logs:/opt/bitnami/spark/logs'
      - '/var/www/trend_metrics/spark/conf:/opt/bitnami/spark/conf'
      - '/var/www/trend_metrics/spark/apps:/opt/spark-apps'
      - '/var/www/trend_metrics/spark/data:/opt/spark-data'
    depends_on:
      - spark-master
    networks:
      - network

  postgresql:
    image: 'postgres:11.7-alpine'
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    networks:
      - network


networks:
  network:
    external: true